apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-engine-config
  namespace: trading-bot
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/trading_bot"
  REDIS_URL: "redis://redis:6379"
  OLLAMA_BASE_URL: "http://ollama:11434"
  LOG_LEVEL: "INFO"
  CONSENSUS_THRESHOLD: "0.75"
  AI_ANALYSIS_INTERVAL: "300"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine
  namespace: trading-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-engine
  template:
    metadata:
      labels:
        app: ai-engine
    spec:
      containers:
      - name: ai-engine
        image: trading-bot/ai-engine:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: ai-engine-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: ai-engine-config
              key: REDIS_URL
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: trading-bot-secrets
              key: openai-api-key
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: trading-bot-secrets
              key: deepseek-api-key
        - name: OLLAMA_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: ai-engine-config
              key: OLLAMA_BASE_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ai-engine-config
              key: LOG_LEVEL
        - name: CONSENSUS_THRESHOLD
          valueFrom:
            configMapKeyRef:
              name: ai-engine-config
              key: CONSENSUS_THRESHOLD
        - name: AI_ANALYSIS_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: ai-engine-config
              key: AI_ANALYSIS_INTERVAL
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine
  namespace: trading-bot
spec:
  selector:
    app: ai-engine
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP