apiVersion: v1
kind: Secret
metadata:
  name: trading-bot-secrets
  namespace: trading-bot
type: Opaque
data:
  # Replace these with your actual base64-encoded API keys
  bitpanda-api-key: ""
  bitpanda-api-secret: ""
  openai-api-key: ""
  deepseek-api-key: ""
  news-api-key: ""
  twitter-bearer-token: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: trading-bot
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/trading_bot"
  REDIS_URL: "redis://redis:6379"
  PAPER_TRADING: "true"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: trading-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: trading-bot/api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: REDIS_URL
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: BITPANDA_API_KEY
          valueFrom:
            secretKeyRef:
              name: trading-bot-secrets
              key: bitpanda-api-key
        - name: BITPANDA_API_SECRET
          valueFrom:
            secretKeyRef:
              name: trading-bot-secrets
              key: bitpanda-api-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: trading-bot-secrets
              key: openai-api-key
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: trading-bot-secrets
              key: deepseek-api-key
        - name: PAPER_TRADING
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: PAPER_TRADING
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: trading-bot
spec:
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: trading-bot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80