apiVersion: v1
kind: ConfigMap
metadata:
  name: data-collector-config
  namespace: trading-bot
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/trading_bot"
  REDIS_URL: "redis://redis:6379"
  LOG_LEVEL: "INFO"
  COLLECTION_INTERVAL: "60"
  NEWS_SOURCES: "reuters,bloomberg,coindesk"
  SOCIAL_PLATFORMS: "twitter,reddit"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
  namespace: trading-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
      - name: data-collector
        image: trading-bot/data-collector:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: data-collector-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: data-collector-config
              key: REDIS_URL
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: NEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: trading-bot-secrets
              key: news-api-key
        - name: TWITTER_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: trading-bot-secrets
              key: twitter-bearer-token
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: data-collector-config
              key: LOG_LEVEL
        - name: COLLECTION_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: data-collector-config
              key: COLLECTION_INTERVAL
        - name: NEWS_SOURCES
          valueFrom:
            configMapKeyRef:
              name: data-collector-config
              key: NEWS_SOURCES
        - name: SOCIAL_PLATFORMS
          valueFrom:
            configMapKeyRef:
              name: data-collector-config
              key: SOCIAL_PLATFORMS
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: data-collector
  namespace: trading-bot
spec:
  selector:
    app: data-collector
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP