apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: trading-bot
data:
  REACT_APP_API_URL: "http://api:8000"
  REACT_APP_ENVIRONMENT: "production"
  REACT_APP_WEBSOCKET_URL: "ws://api:8000/ws"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: trading-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: trading-bot/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: REACT_APP_API_URL
        - name: REACT_APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: REACT_APP_ENVIRONMENT
        - name: REACT_APP_WEBSOCKET_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: REACT_APP_WEBSOCKET_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: trading-bot
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP